### ISSUE TITLE
'ValidationError' object has no attribute 'message'

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3309]
See https://grand-challenge.sentry.io/issues/5181371764/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2

Introduced in #3296
