### PR TITLE
Fix ValidationError printing

### LINKED ISSUE #3309: 'ValidationError' object has no attribute 'message'
See https://grand-challenge.sentry.io/issues/5181371764/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2

Introduced in #3296

### PR DESCRIPTION
**Pull request by amickan**
Closes #3309

### CODE REVIEW

File: app/grandchallenge/core/utils/error_messages.py [hunk 1]
```diff
@@ -0,0 +1,7 @@
+def format_error_message(error):
```
Comment (jmsmkn) [inline app/grandchallenge/core/utils/error_messages.py:1]: This is specific to validation errors, right? Only there because of the construction of this class in django.

Comment (amickan) [reply app/grandchallenge/core/utils/error_messages.py:1]: Yes. Should I add a check `if isinstance(error, ValidationError)` and error out if not?

Comment (jmsmkn) [reply app/grandchallenge/core/utils/error_messages.py:1]: I think maybe just rename the method so developers know when to use it.
